# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160314_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='allergies',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='Joseph', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Moran', max_length=32),
            preserve_default=False,
        ),
    ]
